version: '3'
services:
  ############################
  # Go app + Dapr sidecar
  ############################
  goapp:
    build: .
    command: ["./goapp"]
    ports:
      - "50002:50002"
      - "8080:80"
    depends_on:
      - redis
      - placement
    networks:
      - service-network
  goapp-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd",
     "-app-id", "goapp",
     "-placement-host-address", "placement:50006",
     "-components-path", "/components"]
    volumes:
        - "./components/:/components"
    depends_on:
      - goapp
    network_mode: "service:goapp"
  ############################
  # test container + Dapr sidecar
  ############################
  test:
    build: .
    tty: true
    depends_on:
      - redis
      - placement
    networks:
      - service-network
    volumes:
      - "./goapp/testdata:/go/src/testdata"
  test-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd",
     "-app-id", "test",
     "-placement-host-address", "placement:50006",
     "-components-path", "/components"]
    volumes:
        - "./components/:/components"
    depends_on:
      - test
    network_mode: "service:test"
  ############################
  # Dapr placement service
  ############################
  placement:
    image: "daprio/dapr"
    command: ["./placement", "-port", "50006"]
    ports:
      - "50006:50006"
    networks:
      - service-network
  ############################
  # Redis state store
  ############################
  redis:
    image: 'bitnami/redis:latest'
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - service-network
networks:
    service-network:
