apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: mysql-state
spec:
  type: state.mysql
  version: v1
  metadata:
  - name: connectionString
    value: "root:password123@tcp(mysql:3306)/?allowNativePasswords=true"
